import type { ClinicalAnalysis, ClinicalJob, DocumentManifest, Encounter, EncounterDetail, OcrResult, TranscriptionVersion } from '../../functions/src/contracts/clinical';

export const timestamp = '2026-09-23T10:00:00.000Z';
export const sourceHash = 'a'.repeat(64);
export const encounter: Encounter = { id: 'enc-1', patientId: 'SYNTHETIC-P001', ownerUid: 'user-a', organizationId: 'test-org', documentType: 'lab_result', language: 'en', patientContext: { ageRange: 'adult', allergies: ['synthetic allergy'], currentMedications: ['Medicine Alpha', 'Medicine Beta'] }, triage: 'no_red_flags', status: 'draft', referralStatus: 'none', createdAt: timestamp, updatedAt: timestamp };
export const manifest: DocumentManifest = { id: 'doc-1', encounterId: encounter.id, ownerUid: encounter.ownerUid, organizationId: encounter.organizationId, createdAt: timestamp, expiresAt: '2099-09-24T10:00:00.000Z', pages: [{ id: 'page-1', fileName: 'synthetic.png', mimeType: 'image/png', sizeBytes: 4, sha256: sourceHash, storagePath: 'organizations/test-org/users/user-a/encounters/enc-1/documents/doc-1/pages/page-1' }] };
export const ocr: OcrResult = { documentId: manifest.id, processorVersion: 'synthetic-ocr-v1', requiresReview: true, pages: [{ pageNumber: 1, sourcePageId: 'page-1', text: 'Synthetic marker 8.2', confidence: 0.8, qualityReasons: [], tokens: [{ text: '8.2', confidence: 0.7, pageNumber: 1, handwritten: true, boundingBox: [{x: 0.1, y: 0.1}, {x: 0.3, y: 0.1}, {x: 0.3, y: 0.2}, {x: 0.1, y: 0.2}] }] }] };
export const transcription: TranscriptionVersion = { id: 'text-1', documentId: manifest.id, ocrJobId: 'job-ocr', text: 'Synthetic marker 8.2', reviewed: true, reviewerUid: encounter.ownerUid, reviewedAt: timestamp, sourceHashes: [sourceHash] };
export const analysis: ClinicalAnalysis = { urgency: 'unknown', possibleFindings: [{ name: 'Synthetic document finding', likelihood: 'uncertain', observedEvidence: ['Synthetic marker 8.2'], markers: ['synthetic-marker'], medicationSafetyNotes: [], traditionalRemedyWarnings: [], reasoning: 'A synthetic test fixture, not clinical guidance.', recommendedNextSteps: ['Clinician document review'], clinicianReviewRequired: true }], markers: [{id: 'synthetic-marker',label: 'Synthetic marker',value: '8.2', status: 'review_required', color: 'gray'}], contraindications: [], limitations: ['Synthetic engineering fixture only.'], disclaimer: 'Not a diagnosis or prescription.', medicationAssessment: 'not_assessed', provenance: { model: 'Synthetic fixture', modelVersion: 'test-v1', promptVersion: 'test-v1', schemaVersion: 'clinical-v1', analyzedAt: timestamp, documentId: manifest.id, transcriptionId: transcription.id, sourceHashes: [sourceHash] } };
export const ocrJob: ClinicalJob = { id: 'job-ocr',encounterId: encounter.id,documentId: manifest.id,kind: 'ocr',status: 'succeeded',attempts: 1,createdAt: timestamp,updatedAt: timestamp,resultId: 'job-ocr',result: ocr };
export const analysisJob: ClinicalJob = { id: 'job-analysis',encounterId: encounter.id,documentId: manifest.id,kind: 'analysis',status: 'succeeded',attempts: 1,createdAt: timestamp,updatedAt: timestamp,resultId: 'analysis-1',result: analysis };
export const detail: EncounterDetail = { encounter, documents: [manifest], transcriptions: [], analyses: [], reviews: [], jobs: [] };
export const analyzedDetail: EncounterDetail = { encounter: { ...encounter, status: 'review_required', latestTranscriptionId: transcription.id, latestAnalysisId: 'analysis-1' }, documents: [manifest], transcriptions: [transcription], analyses: [{id: 'analysis-1',result: analysis}], reviews: [], jobs: [analysisJob, ocrJob] };
export const pendingPage = {id:'page-1',fileName:'synthetic.png',mimeType:'image/png',contentBase64:'data:image/png;base64,AAAA'};
